name: Run Bot Daily at 19:45 WIB

on:
  schedule:
    - cron: '00 13 * * *'  # 19:45 WIB (UTC+7) = 12:45 UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schedule==1.2.2 \
                      oauth2client==4.1.3 \
                      oauthlib==3.2.2 \
                      google-auth==2.30.0 \
                      google-auth-oauthlib==1.2.0 \
                      gspread==6.1.2 \
                      gspread-formatting==1.1.2 \
                      google-api-python-client==2.126.0 \
                      python-telegram-bot==13.15

      - name: Create Google credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDS }}" > creds.json

      - name: Run bot.py script
        run: |
          python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TEAMUP_TOKEN: ${{ secrets.TEAMUP_TOKEN }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
