name: Run Bot at D-DAY 10:00 WIB

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 06:30 WIB = 23:30 UTC (hari sebelumnya)

    
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schedule==1.2.2 \
                      oauth2client==4.1.3 \
                      oauthlib==3.2.2 \
                      google-auth==2.30.0 \
                      google-auth-oauthlib==1.2.0 \
                      gspread==6.1.2 \
                      gspread-formatting==1.1.2 \
                      google-api-python-client==2.126.0 \
                      python-telegram-bot==20.6 \
                      pytz  

      - name: Create Google credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDS }}" > creds.json

      - name: Run botnow.py script
        run: |
          python botnow.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TEAMUP_TOKEN: ${{ secrets.TEAMUP_TOKEN }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: agenda-pdf
          path: agenda_*.pdf
